'use client'
import { Header } from '@components/layout'
import './globals.css'
import { Container } from '@mui/material'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Header />
      <body>
        <Container maxWidth='lg'>
          {children}
        </Container>
      </body>
    </html>
  )
}
